### PR TITLE
Merge market watcher

### PR DESCRIPTION
**Pull request by ghost**
This is to change faig.py to make use of market_watcher module.

Recent commit  #11 includes certain improvements (e.g. use of stream API, allow setting minimum spread for individual epic), which are still not reflected in this version.

This merge is to consolidate the module at an earlier stage to make sure we do not work of the same task. The improvements mentioned will be incorporate into the market_watcher module soon.

Please comment.

### CODE REVIEW

**Comment by tg12** [comment]
Hi, Not sure if this works. Whilst market watcher might work we still need to find an epic to trade on.

**Comment by ghost** [comment]
Could you elaborate?
Currently the watcher will looks for epic with price change and spread within range, that when this happens, an epic will be returned. Is this not the expected result?

```
# Watch market for opportunity.
    watcher = MarketWatcher(client=igclient, epics=list(epics), change_range=(0.48, 1.9), spread_range=(0.0, 2.0))
    watcher.watch()
    epic_id = watcher.epic
    current_price = watcher.bid
```

**Comment by FlickeringIRoam** [comment]
In general, it's not worth submitting a pull just to change formatting to add/remove a space.  Clean code is nice, but it kind of messes with the history/blame.  It makes it very hard to see actual changes.  Could you remove all the formatting (they'll probably get fixed over time eventually) and resubmit?

**Comment by ghost** [comment]
I apologise for that. My IDE incorporated AutoPEP8, which will automatically convert the code to proper format on save. I try to put all these auto stuffs to an individual commit. To view changes other than them, you may view this commit (https://github.com/tg12/FAIG/pull/17/commits/f416caf9a2330921fe0a7dfe6875b9a457cade46).

Sorry about that.

**Comment by FlickeringIRoam** [comment]
No problem, i figured it'd be something like that.

it's handy to export the function out into a separate module, after moving
it to a subroutine that was the plan, but other things always came first.
You have dropped a lot of the config lookups and replaced it with hardcoded
vals.  I don't know if people are just going to stick with the defaults or
use their own safer/riskier values, but it's a shame to lose that, and the
hardcoded spread of 2.0 has since been replaced, since many of the exotics
cannot ever have a spread that low.  But again, through the config you can
choose to only use those values, or to use the more dynamic method of
determining spread risk.

Could you use the config values rather than the hardcoded, and also use the
dynamic spread options that permit the exotics?

There's also the changes to skip an epic of we already have an open trade
on it that'll need merging, but i suspect that'll go straight in.

**Comment by ghost** [comment]
Thanks for your comment!! Definitely will need a lot guidance when catching up new project. 

I try to summarise the missing features per your comment. 

1) for price and spread, instead of hard coding them, get them from config file. 
2) add a feature to exclude epic with opened position in the watching list. 

Could you comment?

**Comment by FlickeringIRoam** [comment]
#2 is already done in the latest master, if you just run "git pull upstream
master" it will attempt to merge the latest changes into your code.  Since
the changes for #2 effect your module, it probably won't merge in cleanly,
but it's a very simple way of implementing it, so after a pull it'll take 2
mins to transfer it to your module, since that already implements igclient

**Comment by ghost** [comment]
Could you help me on this?

I try to make use of igstream module. However, looks like I cannot fetch data from it. Below are the stdout.

```
2018-02-28 22:44:10,817 Starting new HTTPS connection (1): demo-api.ig.com
2018-02-28 22:44:11,288 https://demo-api.ig.com:443 "POST /gateway/deal/session HTTP/1.1" 200 355
2018-02-28 22:44:11,295 Starting new HTTPS connection (1): demo-api.ig.com
2018-02-28 22:44:11,691 https://demo-api.ig.com:443 "GET /gateway/deal/accounts HTTP/1.1" 200 242
2018-02-28 22:44:11,698 Starting new HTTPS connection (1): demo-api.ig.com
2018-02-28 22:44:11,960 https://demo-api.ig.com:443 "PUT /gateway/deal/session HTTP/1.1" 400 75
2018-02-28 22:44:11,964 Starting connection
2018-02-28 22:44:13,208 Waiting for a new message
2018-02-28 22:44:14,418 Server response ---> <ERROR>
2018-02-28 22:44:18,205 Received message ---> <PROBE>
2018-02-28 22:44:18,205 PROBE message
2018-02-28 22:44:18,206 Waiting for a new message
2018-02-28 22:44:23,214 Received message ---> <PROBE>
2018-02-28 22:44:23,214 PROBE message
2018-02-28 22:44:23,214 Waiting for a new message
2018-02-28 22:44:28,213 Received message ---> <PROBE>
2018-02-28 22:44:28,213 PROBE message
2018-02-28 22:44:28,214 Waiting for a new message
```

**Comment by FlickeringIRoam** [comment]
Yep, no problem at all.  The igstream module is mostly the lightstreamer
sample code, but it didn't work with IG until i did a couple of days
tweaking.
Can you paste the relevant code that's causing the error?

**Comment by ghost** [comment]
I am cancelling this pull request, since there are some substantial changes in the the [FAIG/faig.py](https://github.com/tg12/FAIG/blob/master/faig.py) and [FAIG/igstream.py](https://github.com/tg12/FAIG/blob/master/igstream.py). Will do another pull request for merging market_watcher module.

**Pull request closed without merging**
